language: r
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

## Don't (attempt to) upload to drat if:
## 1. You're not me (@csgillespie) - change if you fork this repo
## 2. It's a pull request
## 3. We're not on the master branch
after_success:
  - test $TRAVIS_REPO_SLUG == "csgillespie/dratTravis" && test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

## Encrypted token
env:
  global:
   secure: cF2GW3S1oo26KDIrpzRrSNdiWQWMTRnPLoNZk4CnxE2kTKIAZLJP7MFwjDjWRWIoWzl3xqXmLMfolDhqbyY2Hw/jhhvsB/q7Jr61Jy3Et6WNetHj/6bz5MSGXPO5TCR9AyBRM5/DeQTNmYI2zMHZgCVVi45tS2X0ay1/SPIJy3Y=
